### PR TITLE
Resolve problems

### PR DESCRIPTION
**Pull request by mohmdrzaa**

### CODE REVIEW

**Comment by Amirerfan** [comment]
please rebase project and make sure that you are up-to-date.

**Comment by mohmdrzaa** [comment]
> please rebase project and make sure that you are up-to-date.

Yup, I did it! and it was up-to-date!
I haven't made these changes!!!

**Comment by Amirerfan** [comment]
So why there is ForgetPassword.java file in your project ? 
This file has been deleted sense [33ac83](https://github.com/alpha-se-team/shirazu-uni-app/commit/33ac835a11e39534d513972d6feac24e6a84eaf2) commit.

**Comment by mohmdrzaa** [comment]
> So why there is ForgetPassword.java file in your project ?
> This file has been deleted sense [33ac83](https://github.com/alpha-se-team/shirazu-uni-app/commit/33ac835a11e39534d513972d6feac24e6a84eaf2) commit.

idk maybe it only updated with new files and doesn't affect on deleting recent files! I did rebase and got that "Current branch development is up to date." then I did changes

**Comment by Amirerfan** [comment]
> > So why there is ForgetPassword.java file in your project ?
> > This file has been deleted sense [33ac83](https://github.com/alpha-se-team/shirazu-uni-app/commit/33ac835a11e39534d513972d6feac24e6a84eaf2) commit.
> 
> idk maybe it only updated with new files and doesn't affect on deleting recent files! I did rebase and got that "Current branch development is up to date." then I did changes

**Pull request closed without merging**
