### PR TITLE
Fix some login page ui bugs

### PR DESCRIPTION
**Pull request by mohmdrzaa**
Changes:
+ change username and password fields textColor to darkBlue
+ change password field input type to password
+ resolve position of goToCalendar cardView and appeared shadow of its background
+ add incorrect information dialog

### CODE REVIEW

**Comment by alifarazz** [comment]
These commits aren't descriptive of the changes you've made, Mohammad Reza.

**Comment by mohmdrzaa** [comment]
> These commits aren't descriptive of the changes you've made, Mohammad Reza.

which changes do you mean, Ali?
would you help me please to improve it
tnx :)

**Comment by alifarazz** [comment]
Well, in your first comment, you listed 4 main points. I believe each one deserves a commit.

**Review by Amirerfan — CHANGES_REQUESTED** [review]
please change every element's id and color's name from camelCase to snake_case

**Comment by mohmdrzaa** [comment]
> Well, in your first comment, you listed 4 main points in your comment. I believe each one deserves a commit.

Yes, you're right and i'll try to make it better soon :) 
Thanks

**Comment by mohmdrzaa** [comment]
> please change every element's id and color's name from camelCase to snake_case

Yes, I'll do it soon! :) ✌️

**Review by Amirerfan — APPROVED** [review]
nice

**Pull request closed without merging**
